/**
 * Created by jobando on 08-Jun-16.
 */
export default {
  LOGIN: 'AUTHCUSTOMER',
  LOGIN_RESPONSE:'AUTHCUSTOMERRESPONSE',
  COMPANY_INFO: 'COMPANYINFORMATION',
  COMPANY_INFO_RESPONSE:'GETCOMPANYINFORESPONSE',
  COUNTRIES: 'COUNTRIES',
  COUNTRIES_RESPONSE:'COUNTRIESRESPONSE',
  STATES: 'STATES',
  STATES_RESPONSE:'STATESRESPONSE',
  PROCESSORS: 'PROCESSORS',
  PROCESSORS_RESPONSE:'PROCESSORSRESPONSE',
  CUSTOMER_INFO_RESPONSE:'CUSTOMERINFORESPONSE',
  PAYACCOUNTS_BY_PROCESSOR: 'PAYACCOUNTS',
  PAYACCOUNTS_BY_PROCESSOR_RESPONSE:'GETPAYACCOUNTSBYCUSTOMERRESPONSE',
  PROCESSORS_LIMIT_MIN_MAX: 'PROCESSORLIMITMINMAX',
  PROCESSORS_LIMIT_MIN_MAX_RESPONSE:'GETPROCESSORMINMAXLIMITSRESPONSE',
  PROCESSORS_LIMIT_RULES: 'PROCESSORLIMITRULE',
  PROCESSORS_LIMIT_RULES_RESPONSE:'GETPROCESSORLIMITSRESPONSE',
  STOMP_CONNECTION: 'STOMPCONNECTION',
  STOMP_CONNECTION_SUCCESS: 'STOMP_CONNECTION_SUCCESS',
  CHANGE_PROCESSOR:'CHANGE_PROCESSOR'
}