/**
 * Created by jobando on 08-Jun-16.
 */
export default {
  LOGIN: 'AUTHCUSTOMER',
  LOGIN_RESPONSE:'AUTHCUSTOMERRESPONSE',
  COMPANY_INFO: 'COMPANYINFO',
  COMPANY_INFO_RESPONSE:'COMPANYINFORMATIONRESPONSE',
  COUNTRIES: 'COUNTRIES',
  COUNTRIES_RESPONSE:'COUNTRIESRESPONSE',
  STATES: 'STATES',
  STATES_RESPONSE:'STATESRESPONSE',
  PROCESSORS: 'PROCESSORS',
  PROCESSORS_RESPONSE:'PROCESSORSRESPONSE',
  CUSTOMER_INFO_RESPONSE:'CUSTOMERINFORESPONSE',
  STOMP_CONNECTION: 'STOMPCONNECTION',
  STOMP_CONNECTION_SUCCESS: 'STOMP_CONNECTION_SUCCESS'
}