/**
 * Created by jobando on 08-Jun-16.
 */
export default {
  LOGIN: 'LOGIN',
  LOGIN_RESPONSE:'AUTHCUSTOMERRESPONSE',
  CUSTOMERINFO: 'CUSTOMERINFO',
  CUSTOMERINFO_RESPONSE:'CUSTOMERINFORESPONSE',
  STOMP_CONNECTION: 'STOMPCONNECTION'
}