/**
 * Created by jobando on 15-Jun-16.
 */
export default {
	//Views
	VIEW_DEFAULT: 'deposit',
	VIEW_DEPOSIT: 'deposit',
	VIEW_WITHDRAW: 'withdraw',
	// Processors
	PROCESSOR_ID_NETELLER: 333,
	PROCESSOR_ID_BITCOIN: 814,
	PROCESSOR_ID_VISA: 11001,
	PROCESSOR_ID_MONEYGRAM: 16,
	// Processor Class
	PROCESSOR_CLASS_ID_CREDIT_CARDS: 1,
	PROCESSOR_CLASS_ID_E_WALLET: 5,
	PROCESSOR_CLASS_ID_PERSON_2_PERSON: 23,
	// Transaction Status
	TRANSACTION_STATUS_PENDING: 1,
	TRANSACTION_STATUS_APPROVED: 2,
	TRANSACTION_STATUS_REJECTED: 3,
	TRANSACTION_STATUS_FAILED: 4,
	TRANSACTION_STATUS_PROCESSING: 5,
	TRANSACTION_STATUS_CANCELLED: 8,
	TRANSACTION_STATUS_PRE_APPROVE: 22,
	TRANSACTION_STATUS_DEFERRED: 30,

	M_BELOW_MIN: "M_BELOW_MIN",
	M_ABOVE_MAX: "M_ABOVE_MAX",
	LIMIT_NO_ERRORS: "LIMIT_NO_ERRORS"
	
}